(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cfg=window.SEH_CONFIG||window.EHOCKEY_CONFIG||window.APP_CONFIG||window.config||{},BASE=String(cfg.supabaseUrl||cfg.SUPABASE_URL||"").replace(/\/+$/,"")+"/rest/v1/",KEY=String(cfg.supabasePublishableKey||cfg.supabaseAnonKey||cfg.SUPABASE_ANON_KEY||cfg.SUPABASE_PUBLISHABLE_KEY||""),headers=KEY?{apikey:KEY,Accept:"application/json"}:{};if(/^eyJ/i.test(KEY))headers.Authorization="Bearer "+KEY;
const LEAGUE=520;let teams=[],players=[],playoffs=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function get(path){const r=await fetch(BASE+path,{headers});if(!r.ok)throw new Error(path+" "+r.status);return r.json()}
function logo(t){return String(t?.team_logo_in_league||t?.current_global_team_logo||"")}
function team(id){return teams.find(t=>String(t.sports_gamer_team_id)===String(id))||{team_name_in_league:"LAG"}}
function fill(cls,t){$$(cls).forEach(el=>{const im=el.querySelector("img"),b=el.querySelector("b");if(im){im.src=logo(t);im.alt=""}if(b)b.textContent=t.team_name_in_league})}
function pct(n,d){return d?Math.round(100*n/d)+"%":"0%"}function one(n){return Number(n||0).toFixed(1)}
function pimg(p){const id=p?.sports_gamer_player_id;return id?"../../players/"+id+".png":""}
function pos(p){return p.playoff_skater_position_abbreviation||p.roster_preferred_position_abbreviation||p.regular_skater_position_abbreviation||((p.playoff_goalie_games||p.regular_goalie_games)?"G":"")}
function playerCard(p,position){if(!p)return '<div class="player empty"><span>'+position+'</span><div class="sil">?</div><b>SAKNAS</b></div>';return '<div class="player"><span>'+esc(position)+'</span><img src="'+esc(pimg(p))+'" onerror="this.style.display=\'none\'"><div class="player-info"><strong>#'+esc(p.player_number||"")+" "+esc(p.display_gamertag)+'</strong><small>GRUPP '+(p.regular_points||0)+' P · SLUTSPEL '+(p.playoff_points||0)+' P</small></div></div>'}
function lineup(t){const ps=players.filter(p=>String(p.sports_gamer_team_id)===String(t.sports_gamer_team_id));const slots=["LW","C","RW","LD","G","RD"];return slots.map(slot=>{let candidates=ps.filter(p=>pos(p)===slot);if(slot==="G")candidates.sort((a,b)=>(b.playoff_goalie_games||0)-(a.playoff_goalie_games||0));else candidates.sort((a,b)=>(b.playoff_skater_games||0)-(a.playoff_skater_games||0)||(b.playoff_points||0)-(a.playoff_points||0));return playerCard(candidates[0],slot)}).join("")}
function stage(t,s){return teams.find(x=>x.sports_gamer_team_id===t.sports_gamer_team_id&&x.statistics_stage===s)||{}}
function playoff(t){return playoffs.find(x=>x.sports_gamer_team_id===t.sports_gamer_team_id)||{}}
function renderStats(h,a){const hr=stage(h,"regular"),ar=stage(a,"regular"),hp=stage(h,"playoffs"),ap=stage(a,"playoffs");const rows=[[pct(hr.total_wins,hr.games_played),pct(ar.total_wins,ar.games_played),"GRUPP WIN RATE"],[one((hr.goals_for||0)/(hr.games_played||1)),one((ar.goals_for||0)/(ar.games_played||1)),"GRUPP MÅL / MATCH"],[pct(hp.total_wins,hp.games_played),pct(ap.total_wins,ap.games_played),"SLUTSPEL WIN RATE"],[hp.goals_for||0,ap.goals_for||0,"SLUTSPEL MÅL"]];$(".statrows").innerHTML=rows.map(r=>'<div><b>'+r[0]+'</b><span>'+r[2]+'</span><b>'+r[1]+'</b></div>').join("")}
function roadCard(t){const r=stage(t,"regular"),p=stage(t,"playoffs"),po=playoff(t);return '<div class="road-card"><div class="road-team"><img src="'+esc(logo(t))+'"><b>'+esc(t.team_name_in_league)+'</b></div><div class="road-step"><small>GRUPPSPEL</small><strong>#'+esc(po.regular_season_seed||"–")+'</strong><span>'+(r.total_wins||0)+' vinster · '+(r.goals_for||0)+'–'+(r.goals_against||0)+'</span></div><i></i><div class="road-step"><small>SLUTSPEL</small><strong>'+esc(po.series_won||0)+'–'+esc(po.series_lost||0)+' serier</strong><span>'+(p.matched_playoff_game_wins||po.matched_playoff_game_wins||0)+' matchvinster</span></div><i></i><div class="road-step final"><small>NU</small><strong>FINAL</strong><span>'+esc(po.playoff_status_name||"Final")+'</span></div></div>'}
function leaderCard(p){const g=(p.regular_goals||0)+(p.playoff_goals||0),a=(p.regular_assists||0)+(p.playoff_assists||0),pts=(p.regular_points||0)+(p.playoff_points||0);return '<div class="leader-card"><img src="'+esc(pimg(p))+'" onerror="this.style.display=\'none\'"><div><small>'+esc(p.team_name_in_league)+'</small><b>'+esc(p.display_gamertag)+'</b><span>'+g+' G · '+a+' A · <strong>'+pts+' P</strong></span><em>Grupp '+(p.regular_points||0)+' · Slutspel '+(p.playoff_points||0)+'</em></div></div>'}
function render(){const h=team($("#home").value),a=team($("#away").value);fill(".homeTeam",h);fill(".awayTeam",a);$("#lineupTeam").textContent=h.team_name_in_league;$(".players").innerHTML=lineup(h);$("#topTitle").textContent=$("#headline").value;$("#topSub").textContent=$("#subline").value;$("#homeScore").textContent=$("#hs").value||0;$("#awayScore").textContent=$("#as").value||0;$("#personOut").textContent=$("#person").value;$("#roleOut").textContent=$("#role").value;renderStats(h,a);$("#roadGrid").innerHTML=roadCard(h)+roadCard(a);const ids=new Set([String(h.sports_gamer_team_id),String(a.sports_gamer_team_id)]);const leaders=players.filter(p=>ids.has(String(p.sports_gamer_team_id))&&((p.regular_skater_games||0)+(p.playoff_skater_games||0)>0)).sort((a,b)=>((b.regular_points||0)+(b.playoff_points||0))-((a.regular_points||0)+(a.playoff_points||0))).slice(0,4);$("#leaderGrid").innerHTML=leaders.map(leaderCard).join("")}
async function load(){try{const [ts,ps,po]=await Promise.all([get("sportsgamer_team_tournament_stats?select=sports_gamer_team_id,team_name_in_league,team_logo_in_league,statistics_stage,games_played,wins,losses,overtime_wins,overtime_losses,total_wins,table_points,goals_for,goals_against,goal_difference&sports_gamer_league_id=eq."+LEAGUE),get("v_sec21_broadcast_players_public?select=*&sports_gamer_league_id=eq."+LEAGUE),get("sportsgamer_team_playoff_results?select=sports_gamer_team_id,team_name_in_league,regular_season_seed,final_placement,playoff_round_name,playoff_status_name,series_played,series_won,series_lost,matched_playoff_games,matched_playoff_game_wins,matched_playoff_game_losses,final_winner_team_id,final_opponent_team_id,final_team_game_wins,final_opponent_game_wins&sports_gamer_league_id=eq."+LEAGUE)]);teams=ts;players=ps;playoffs=po;const uniq=[...new Map(ts.map(t=>[t.sports_gamer_team_id,t])).values()].sort((a,b)=>a.team_name_in_league.localeCompare(b.team_name_in_league,"sv"));const opts=uniq.map(t=>'<option value="'+t.sports_gamer_team_id+'">'+esc(t.team_name_in_league)+'</option>').join("");$("#home").innerHTML=opts;$("#away").innerHTML=opts;$("#home").value="7046";$("#away").value="3252";$("#headline").value="SEC 21 · BRONSMATCH";$("#subline").value="DAANKERZQUAD vs VÄSTERÅS IK";render()}catch(e){console.error(e);$("#home").innerHTML=$("#away").innerHTML='<option>SEC 21 kunde inte laddas</option>'}}
$$("[data-scene]").forEach(b=>b.onclick=()=>{$$("[data-scene]").forEach(x=>x.classList.toggle("active",x===b));$$(".scene").forEach(x=>x.classList.toggle("active",x.classList.contains(b.dataset.scene)))});
["home","away","hs","as","headline","subline","person","role"].forEach(id=>$("#"+id).addEventListener("input",render));load();
})();