(()=>{
"use strict";
const SUPABASE_URL="https://oujqnvrczdavqbqaavuh.supabase.co";
const SUPABASE_KEY="sb_publishable_-4cV-I1xCAAZrgdcGCljrQ_T7T0YC5z";
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const buttons=[...document.querySelectorAll("[data-sync]")];
const authState=document.getElementById("authState");
const note=document.getElementById("syncNote");
let session=null,isAdmin=false,busy=false;
const fmtDate=value=>{if(!value)return "Aldrig";try{return new Intl.DateTimeFormat("sv-SE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}catch{return "Okänd tid"}};
const setButtons=()=>buttons.forEach(b=>b.disabled=!isAdmin||busy);
async function loadAdmin(){try{const result=await client.auth.getSession();session=result.data.session||null;if(!session){authState.textContent="INTE INLOGGAD";authState.className="auth-state bad";note.textContent="Logga in på Svensk eHockey i samma webbläsare för att köra synkning.";setButtons();return;}const writer=await client.rpc("seh_current_writer");const row=Array.isArray(writer.data)?writer.data[0]:writer.data;isAdmin=Boolean(row&&row.role==="admin");authState.textContent=isAdmin?"ADMIN ANSLUTEN":"SAKNAR ADMINRÄTTIGHET";authState.className="auth-state "+(isAdmin?"ok":"bad");note.textContent=isAdmin?"Redo. Synkningen läser SportsGamer i read-only-läge och uppdaterar Broadcast Studio-datan.":"Kontot är inloggat men är inte admin.";setButtons();}catch(e){console.error(e);authState.textContent="AUTH-FEL";authState.className="auth-state bad";setButtons();}}
async function loadStatus(){try{const result=await client.from("v_broadcast_sync_status").select("*").order("sports_gamer_league_id");if(result.error)throw result.error;const byId=new Map((result.data||[]).map(r=>[Number(r.sports_gamer_league_id),r]));const render=(id,el)=>{const r=byId.get(id);document.getElementById(el).textContent=r?(String(r.teams||0)+" lag · "+String(r.players||0)+" spelare · "+fmtDate(r.source_updated_at)):"Ingen data";};render(527,"meta-scl");render(529,"meta-fcl");render(523,"meta-wecl");const g=[524,525,526].map(id=>byId.get(id)).filter(Boolean);const teams=g.reduce((n,r)=>n+Number(r.teams||0),0),players=g.reduce((n,r)=>n+Number(r.players||0),0);const dates=g.map(r=>r.source_updated_at).filter(Boolean).sort();const latest=dates.length?dates[dates.length-1]:null;document.getElementById("meta-gcl").textContent=String(teams)+" lag · "+String(players)+" spelare · "+fmtDate(latest);}catch(e){console.error(e);}}
async function callSync(body){if(!session)throw new Error("Ingen aktiv session.");const res=await fetch(SUPABASE_URL+"/functions/v1/seh-admin-sync",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await res.json().catch(()=>({}));if(!res.ok)throw new Error(payload.error||("HTTP "+res.status));return payload;}
async function poll(requestId){for(let i=0;i<120;i++){await new Promise(r=>setTimeout(r,3000));const s=await callSync({action:"status",job:"broadcast_league_rosters",request_id:requestId});if(s.state==="completed"){if(s.conclusion!=="success")throw new Error("Synkningen avslutades med "+(s.conclusion||"fel")+".");return s;}}throw new Error("Synkningen tog för lång tid.");}
function buttonLabel(ids){if(ids==="523,524,525,526,527,529")return "UPPDATERA ALLA";if(ids==="524,525,526")return "UPPDATERA GCL";if(ids==="527")return "UPPDATERA SCL";if(ids==="529")return "UPPDATERA FCL";return "UPPDATERA WECL";}
buttons.forEach(button=>button.addEventListener("click",async()=>{if(!isAdmin||busy)return;busy=true;setButtons();button.classList.add("running");button.textContent="KÖR…";const ids=button.dataset.sync;const original=buttonLabel(ids);const requestId="broadcast_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8);try{note.textContent="Synkning startad…";await callSync({action:"start",job:"broadcast_league_rosters",request_id:requestId,league_ids:ids});await poll(requestId);note.textContent="Synkningen är klar.";await loadStatus();}catch(e){console.error(e);note.textContent="Fel: "+e.message;}finally{busy=false;button.classList.remove("running");button.textContent=original;setButtons();}}));
setButtons();Promise.all([loadAdmin(),loadStatus()]);
})();