const USER_PLACES = [
  {
    id: "sollentunavagen-166",
    name: "Sollentunavägen 166",
    city: "Sollentuna",
    source: "Egen data",
    description: "Sollentunavägen 166, 191 48 Sollentuna.",
    lat: 59.42975,
    lon: 17.952222,
    image: "./pics/sollentunavagen-166-1.png",
  },
  {
    id: "emblavagen-2",
    name: "Emblavägen 2",
    city: "Sollentuna",
    source: "Egen data",
    description: "Emblavägen 2, 191 49 Sollentuna.",
    lat: 59.445861,
    lon: 17.943667,
  },
  {
    id: "kungstradgarden",
    name: "Kungsträdgården",
    city: "Stockholm",
    source: "Visit Stockholm + Koordinater.se",
    description: "Sveriges mest kända plats för körsbärsblomning mitt i centrala Stockholm.",
    lat: 59.330914,
    lon: 18.072224,
    image: "./pics/kungstradgarden-1.jpg",
  },
  {
    id: "bysistappan",
    name: "Bysistäppan / Bysistorget",
    city: "Stockholm",
    source: "Visit Stockholm + Koordinater.se",
    description: "Visit Stockholm lyfter Bysistorget som en av stadens fina körsbärsblomningsplatser.",
    lat: 59.318253,
    lon: 18.055049,
  },
  {
    id: "lumaparken",
    name: "Lumaparken",
    city: "Stockholm",
    source: "Visit Stockholm + Koordinater.se",
    description: "Visit Stockholm nämner Lumaparken i Hammarby Sjöstad som en bra plats för körsbärsblomning.",
    lat: 59.304611,
    lon: 18.096337,
  image: "./pics/Lumaparken.webp",
  },
  {
    id: "goteborg-botaniska",
    name: "Göteborgs botaniska trädgård",
    city: "Göteborg",
    source: "Botaniska + Göteborg & Co",
    description: "Botaniska firar hanami när körsbärsblomningen är som finast i trädgården.",
    lat: 57.68177,
    lon: 11.9537,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5a/G%C3%B6teborgs_botaniska_tr%C3%A4dg%C3%A5rd-IMG_6638.JPG",
  },
  {
    id: "seminarieparken",
    name: "Seminarieparken",
    city: "Göteborg",
    source: "Göteborg & Co + Koordinater.se",
    description: "Liten park i Linnéstaden som Göteborg lyfter fram för sina vackra körsbärsträd och körsbärsblomning.",
    lat: 57.691376,
    lon: 11.955277,
  },
  {
    id: "jarntorget",
    name: "Järntorget",
    city: "Göteborg",
    source: "Göteborg & Co + Koordinater.se",
    description: "Göteborg & Co beskriver Järntorget som en populär plats när körsbärsträden blommar.",
    lat: 57.699826,
    lon: 11.95369,
  },
  {
    id: "slottsskogen-prunus",
    name: "Slottsskogen",
    city: "Göteborg",
    source: "CherryBlossomTree.com + Koordinater.se",
    description: "Bredare körsbärsblomningskandidat i Göteborg, ofta nämnd för sin prunusallé på våren.",
    lat: 57.687205,
    lon: 11.947951,
  },
  {
    id: "tradgardsforeningen-goteborg",
    name: "Trädgårdsföreningen",
    city: "Göteborg",
    source: "CherryBlossomTree.com + Koordinater.se",
    description: "Bredare vårblomningskandidat där flera körsbärssorter nämns i reseguider om Göteborg.",
    lat: 57.704929,
    lon: 11.974292,
  },
  {
    id: "borjeparken",
    name: "Börjeparken / Finn Malmgrens plan",
    city: "Uppsala",
    source: "Uppsala kommun + Koordinater.se",
    description: "Uppsala kommun beskriver parken som känd för sina japanska körsbärsträd.",
    lat: 59.860744,
    lon: 17.627394,
  },
  {
    id: "siegbahnsparken",
    name: "Siegbahnsparken",
    city: "Uppsala",
    source: "Uppsala kommun + Koordinater.se",
    description: "I parkdelen Körsbärsdalen finns blommande körsbärsträd.",
    lat: 59.814011,
    lon: 17.615105,
  },
  {
    id: "nilstorpsangen",
    name: "Nilstorpsängen",
    city: "Lund",
    source: "Lunds kommun + Koordinater.se",
    description: "Lunds kommun beskriver parken som rosa när körsbärsträden blommar under våren.",
    lat: 55.692316,
    lon: 13.198141,
  },
  {
    id: "lunds-botaniska",
    name: "Botaniska trädgården",
    city: "Lund",
    source: "CherryBlossomTree.com + Lunds universitet",
    description: "Bredare vårblomningskandidat; reseguide lyfter Botan som en av Lunds fina blomningsplatser.",
    lat: 55.70474,
    lon: 13.20321,
  },
  {
    id: "hyllie-vattenpark",
    name: "Hyllie vattenpark",
    city: "Malmö",
    source: "Malmö stad + Koordinater.se",
    description: "Malmö stad skriver att parken har cirka 130 körsbärsträd i flera rosa nyanser.",
    lat: 55.565286,
    lon: 12.978819,
    image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Hyllie_vattenpark%2C_Malm%C3%B6%2C_april_2023.jpg",
  },
  {
    id: "nangijalalekplatsen",
    name: "Nangijalalekplatsen",
    city: "Oxie",
    source: "Malmö stad + Koordinater.se",
    description: "Malmö stad beskriver gårdshusen som omgivna av körsbärsträd.",
    lat: 55.531766,
    lon: 13.08486,
  },
  {
    id: "pildammsparken",
    name: "Pildammsparken",
    city: "Malmö",
    source: "CherryBlossomTree.com + Koordinater.se",
    description: "Bredare körsbärsblomningskandidat i södra Sverige med stor parkmiljö och vårblomning.",
    lat: 55.590208,
    lon: 12.99197,
  },
  {
    id: "henry-allards-park",
    name: "Henry Allards park",
    city: "Örebro",
    source: "Örebro kommun + Koordinater.se",
    description: "Örebro kommun beskriver parken som känd för rosablommande japanska körsbärsträd.",
    lat: 59.274808,
    lon: 15.21558,
  },
  {
    id: "korsbarsdalen-umea",
    name: "Körsbärsdalen",
    city: "Umeå",
    source: "Umeå kommun + Namnkartan",
    description: "Park med många fruktbärande och blommande träd, bland annat olika körsbärsträd.",
    lat: 63.8153,
    lon: 20.2446,
  },
  {
    id: "obacka-strandpark",
    name: "Öbacka strandpark",
    city: "Umeå",
    source: "Umeå kommun",
    description: "Umeå kommun nämner bergskörsbär i parkens växtlista; mer blomningskandidat än klassisk sakuraplats.",
    lat: 63.8245,
    lon: 20.2762,
  },
  {
    id: "korsbarsgarden-gotland",
    name: "Körsbärsgården",
    city: "Sundre, Gotland",
    source: "Körsbärsgården + Koordinater.se",
    description: "Gotländsk trädgårds- och konstplats med tydlig körsbärsprofil.",
    lat: 56.9324,
    lon: 18.1686,
  },
  {
    id: "tradgardsforeningen-linkoping",
    name: "Trädgårdsföreningen",
    city: "Linköping",
    source: "Corren + Koordinater.se",
    description: "Linköpings stadsträdgårdsmästare pekar ut Trädgårdsföreningen som en fin plats för körsbärsblomning.",
    lat: 58.405604,
    lon: 15.620888,
  },
  {
    id: "sankt-larsparken-linkoping",
    name: "Sankt Larsparken",
    city: "Linköping",
    source: "Corren + Koordinater.se",
    description: "Corren lyfter Sankt Larsparken som en plats där bergkörsbären börjar blomma tidigt på våren.",
    lat: 58.411799,
    lon: 15.626266,
  },
  {
    id: "tradgardsforeningen-drottninggatan",
    name: "Trädgårdsföreningen, entrén vid Drottninggatan",
    city: "Linköping",
    source: "Corren + Koordinater.se",
    description: "Lokal vårblomningspunkt där japanska körsbär nämns nära entrén vid Drottninggatan.",
    lat: 58.405604,
    lon: 15.620888,
  },
  {
    id: "furutorpsplatsen",
    name: "Furutorpsplatsen",
    city: "Helsingborg",
    source: "Trfihi Parks + Koordinater.se",
    description: "Park som beskrivs som särskilt fin när körsbärsblomningen i nordvästra delen slår ut.",
    lat: 56.037529,
    lon: 12.707678,
  },
  {
    id: "stadsparken-helsingborg",
    name: "Stadsparken",
    city: "Helsingborg",
    source: "CherryBlossomTree.com + Koordinater.se",
    description: "Bredare vårblomningskandidat i Helsingborgs stadsparksmiljö.",
    lat: 56.043047,
    lon: 12.699352,
  },
  {
    id: "norrviken-korsbarstradgarden",
    name: "Norrvikens Körsbärsträdgård",
    city: "Båstad",
    source: "Norrviken + Koordinater.se",
    description: "Norrviken beskriver sin körsbärsträdgård som ett rosaskimrande hav av japanska prydnadskörsbär.",
    lat: 56.448718,
    lon: 12.792043,
  },
  {
    id: "karl-johans-park",
    name: "Karl Johans park",
    city: "Norrköping",
    source: "NT + Koordinater.se",
    description: "Här finns ett ovanligt körsbärsträd som lokalt har uppmärksammats som unikt.",
    lat: 58.594947,
    lon: 16.183968,
  },
  {
    id: "repslagaregatan-norrkoping",
    name: "Repslagaregatan",
    city: "Norrköping",
    source: "NT + ungefärlig punkt från Koordinater.se",
    description: "Lokalt känd gata där japanskt körsbärsträd blommar mitt i stan på våren.",
    lat: 58.588586,
    lon: 16.188679,
  },
  {
    id: "karleksparken-norrtalje",
    name: "Kärleksparken",
    city: "Norrtälje",
    source: "Norrtälje kommun + ungefärlig punkt från Koordinater.se",
    description: "Norrtälje kommun skriver att parken fylls av blommande körsbärsträd på våren.",
    lat: 59.758396,
    lon: 18.707222,
  },
];
