name: Temporary Export Current Profile Files
on:
  push:
    paths:
      - '.github/workflows/export-current-profile-files-temp.yml'
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: current-profile-files
          path: |
            app.js
            index.html
          if-no-files-found: error
          retention-days: 1
